api_version = "2026-04"
[[extensions]]
name = "Conditional Shipping Discount"
handle = "conditional-shipping-discount"
type = "function"
description = "Executable conditional shipping discount reference."
[[extensions.targeting]]
target = "cart.delivery-options.discounts.generate.run"
input_query = "src/cart_delivery_options_discounts_generate_run.graphql"
export = "cart-delivery-options-discounts-generate-run"
[extensions.build]
command = ""
path = "dist/function.wasm"
