api_version = "2026-04"
[[extensions]]
name = "Order Subtotal Discount"
handle = "order-subtotal-discount"
type = "function"
description = "Apply a fixed order discount above an eligible subtotal threshold."
[[extensions.targeting]]
target = "cart.lines.discounts.generate.run"
input_query = "src/cart_lines_discounts_generate_run.graphql"
export = "cart-lines-discounts-generate-run"
[extensions.build]
command = ""
path = "dist/function.wasm"
