api_version = "2026-04"
[[extensions]]
name = "Vip Discount"
handle = "vip-discount"
type = "function"
description = "Executable vip discount reference."
[[extensions.targeting]]
target = "cart.lines.discounts.generate.run"
input_query = "src/cart_lines_discounts_generate_run.graphql"
export = "cart-lines-discounts-generate-run"
[extensions.build]
command = ""
path = "dist/function.wasm"
